# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Rachel S. Bagwell
#title: Your job title
email: rachelsbagwell@gmail.com
# email_title: Email (Email title override)
phone: 9255778412
# phone_title: Phone (Phone title override)
#website: Your website (eg. https://google.com)(optional)
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
# Social links
#twitter_username: jekyllrb
#github_username:  jekyll
#stackoverflow_username: "00000001"
#dribbble_username: jekyll
#facebook_username: jekyll
#flickr_username: jekyll
#instagram_username: jekyll
linkedin_username: http://www.linkedin.com/rachel-bagwell
#xing_username: jekyll
#pinterest_username: jekyll
#youtube_username: jekyll
#googleplus_username: +jekyll
#orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: Link name
#  icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#  url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: Directory of profile image (eg. images/profile.jpg)
about_content: | # this will include new lines to allow paragraphs
  Early Career Data Scientist with a B.S. in Applied Mathematics.  2+ years of academic data science research and  5+ years of CS internship experience.  Proficient in utilizing Python and  MATLAB to create and deliver predictive models utilizing billions of data points for applications in robotics, physics and cyber security. Aspiring to complete Azure Data Scientist Associate certificate with current practical knowledge of Machine Learning, Deep learning,  Data Visualization with Power BI and Apache Spark with Azure Databricks. Capable of creating, developing, testing, and employing data-intensive applications and models to translate business and functional qualifications into substantial deliverables. 
#    - Lists
#    - Tables
#    - <a href="google.com">Links</a>
#    - Images ![alt text](/images/landscape-trees.jpg "Trees")
content:
 # - title: Projects # Title for the section
 #   layout: list # Type of content section (list/text)
 #   content:
 #     - layout: left
 #       title: Project name
 #       link: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
 #       link_text: Link Text
 #       additional_links:
  #        - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #          icon: fab fa-github
  #          url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
  #        - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #          icon: fab fa-github
  #          url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
  #      quote: >
  #        Short overview of the project (optional)
  #      description: | # this will include new lines to allow paragraphs
  #        Description about the work on/with the project
  - title: Experience
    layout: list
    content:
      - layout: right
        title: RoME Lab, DePaul University
        sub_title: Robotics Researcher
        caption: April 2021 - July 2021
        #link: Link to company (optional)
        #quote: >
        #  Short description of the company (optional)
        description: | # this will include new lines to allow paragraphs
          •	Researched bioinspired soft continuum robotic technologies through the Robotics and Medical Engineering (RoME) laboratory at DePaul University.
          •	Utilizing Periodic functions, 3D transformations  and liner algebra, created a novel model that controls a tetrahedral robot’s movement, reproducing the natural slithering of a snake’s movement with MATLAB and Python. 
          •	Created robotic and model acceptance criteria and physics movement simulations in MATLAB and PyBullett. 
      
      - layout: right
        title: Physics Department, DePaul University
        sub_title: Data Science Researcher
        caption: June 2019 - August 2019
        #link: Link to company (optional)
        #quote: >
        #  Short description of the company (optional)
        description: | # this will include new lines to allow paragraphs
          •	Conduct correlation analysis to conclude glaxy Homogeneity from the Sloan Digital Sky Survey Dataset (SDSS) under Jesus Pando At DePaul University. 
          •	Utilizing  Poisson distributions,  Time-Series and Regression analysis to Analyze over 3.4 billion rows and 818gb of Image data using MATLAB, SQL and Python. 
          •	SQL scripting for data cleaning Data preparation, cleaning 

      - layout: right
        title: RIMCO LLC, San Juan, PR
        sub_title: Marketing Intern
        caption: November 2018 - December 2018
        #link: Link to company (optional)
        #quote: >
        #  Short description of the company (optional)
        description: | # this will include new lines to allow paragraphs
         •	Developed skills in networking, communications and general business knowledge. Practiced use and understanding of a foreign language, Spanish. Assisted departments in accomplishing year-end goals 
      
      - layout: right
        title: Lawrence Livermore National Laboratory
        sub_title: Global Security Intern, Marketing Intern
        caption: June 2017 - August 2017, June 2016 - August 2016
        #link: Link to company (optional)
        #quote: >
        #  Short description of the company (optional)
        description: | # this will include new lines to allow paragraphs
         •	Completed computer science summer immersion internship focused on JavaScript, HTML, Python, and CSS. Chose as one of the two Alumni Ambassadors for our internship class.
         •	Completed global and cyber security focused coding exercises, and challenges using Python, networking, and Bluetooth hacking programming tools. Learned about the importance of cybersecurity and focused on summers-end research project	

  - title: Education
    layout: list
    content:
      - layout: top-right
        title: DePaul University
        sub_title: BS Mathematical Sciences, concentration in Computational and Applied Math
        caption: August 2017 - June 2021
        #quote: >
         # Short institution or course description (optional)
        description: | # this will include new lines to allow paragraphs
          GPA: 3.63 (Cum Laude) Honors Program
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      This is where you can write a little more about yourself. You could title this section **Interests** and include some of your other interests.
      Or you could title it **Skills** and write a bit more about things that make you more desirable, like *leadership* or *teamwork*
# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]